# What projective transformation does

(https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.ProjectiveTransform)

For each homogeneous coordinate $𝐱=[𝑥,𝑦,1]^𝑇$, its target position is calculated by multiplying with the given matrix, 𝐻, to give 𝐻𝐱

```
[[a0 a1 a2]
 [b0 b1 b2]
 [c0 c1 1 ]].
```

E.g., to rotate by theta degrees clockwise, the matrix should be:

```
[[cos(theta) -sin(theta) 0]
 [sin(theta)  cos(theta) 0]
 [0            0         1]]
```

or, to translate x by 10 and y by 20:

```
[[1 0 10]
 [0 1 20]
 [0 0 1 ]].
```




## Task 1:

Write a program, that applays pojection transformation to a given image and displays both original image and 
transformed image.

In [1]:
# TODO: your code goes here

Example:

![alt text](transformed.png "TRansformation")

## Task 2:

We are going to use least-square method in order to find good fitting projective transformation based on pairs of matching points at different photos.
As a warm up let's solve a simple example:

Using https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html fit a plane $z = ax + by + c$ to the following data points:

```
x y z
0 1 2.5
1 2 2.5
2 3 4
3 4 6
```


# Task 3:
Write a program that finds a projective transformation based on sequence of point coordinates

The projective transformation is defined as:

```
X = (a0*x + a1*y + a2) / (c0*x + c1*y + 1)
Y = (b0*x + b1*y + b2) / (c0*x + c1*y + 1)
```

These equations can be transformed to the following form:

```
0 = a0*x + a1*y + a2 - c0*x*X - c1*y*X - X
0 = b0*x + b1*y + b2 - c0*x*Y - c1*y*Y - Y
```

which exist for each set of corresponding points, so we have a set of N * 2 equations. The coefficients appear linearly so we can write A x = 0, where:

```
A   = [[x y 1 0 0 0 -x*X -y*X -X]
       [0 0 0 x y 1 -x*Y -y*Y -Y]
        ...
        ...
      ]
x.T = [a0 a1 a2 b0 b1 b2 c0 c1 c3]
```

In case of total least-squares the solution of this homogeneous system of equations is the right singular vector of A which corresponds to the smallest singular value normed by the coefficient c3.

Weights can be applied to each pair of corresponding points to indicate, particularly in an overdetermined system, if point pairs have higher or lower confidence or uncertainties associated with them. From the matrix treatment of least squares problems, these weight values are normalised, square-rooted, then built into a diagonal matrix, by which A is multiplied.

In case of the affine transformation the coefficients c0 and c1 are 0. Thus the system of equations is:

```
A   = [[x y 1 0 0 0 -X]
       [0 0 0 x y 1 -Y]
        ...
        ...
      ]
x.T = [a0 a1 a2 b0 b1 b2 c3]
```


Now as we know how images get transformed let's take two photos with the car cameras. There should be 
rather big overlap (60% is ok) between those photos.

# Task 4:
Take two photos and undistort it

# Task 5:

Mark a few (five is ok) points that are visible on both images by hand. Find a projective transformation between right and left photo.

# Task 6:

Using the projective transormation you have already found stitch two photos into one. In order to do so:

1. Keep one (in example we keep the right) of images unchanged as base, transform the left image using found transformation.
2. Make a new image and put both images into this image.
3. On area overlaping set point colors as weighted average of coresponding pixel (weight can be based on distance from left and right sides of overlapping areas) 

Now the crazy part. So far we have matched points on two photos by hand.
It is neither convinient nor usefull.
There are many methods of matching points on images. SIFT, SURF and ORB (https://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.ORB) are commonly used. However we want to use State Of The Art SuperGlue.

https://github.com/kciebiera/SuperGluePretrainedNetwork

The repository comes with `./match_pairs.py` script, which allows to easily find matches.

# Task 7

Find matches on your photos using `./match_pairs.py` script from SuperGlue repo.


# Task 8

Some of the maches are incorrect. Get rid of those matches using RANSAC with projective transformataion.

# Task 9

Write a program, that can make panorama stiching from two photos (like in point 6) using SuperGlue as a matching method.